[[main]]
  name       = "Series"
  identifier = "series-nav"
  url        = "/series/"
  weight     = 10

[[main]]
  name   = "Demystified"
  parent = "series-nav"
  url    = "/demystified/"
  weight = 11

[[main]]
  name   = "Penny for a Thought"
  parent = "series-nav"
  url    = "/penny-for-a-thought/"
  weight = 12

[[main]]
  name   = "Browse All Posts"
  parent = "series-nav"
  url    = "/posts/"
  weight = 20

[[main]]
  identifier = "linkedin"
  pre        = "linkedin"
  url        = "https://www.linkedin.com/in/compscicarlos/"
  weight     = 100

[[footer]]
  name    = "Tags"
  pageRef = "tags"
  weight  = 10

[[footer]]
  name    = "Series"
  pageRef = "series"
  weight  = 20
